version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: user123
      POSTGRES_DB: projeto-hoteis
    volumes:
      - ./data:/data/postgres

  app:
    image: my-node-app
    ports:
      - 9000:3000
    depends_on:
      - db
    command: sh -c "sleep 10 && npm run db-create && npm run dev"