###
GET http://localhost:9000/hotels

###
POST http://localhost:9000/hotels/insert/
Content-Type: application/json

{
    "name": "Hotel 5 Estrelas",
    "address": "Rio do Sul - SC",
    "room": "205",
    "available": true
}

###
POST http://localhost:9000/hotels/where/
Content-Type: application/json

{
    "address": "Rio do Sul - SC",
    "available": true
}